language: c
sudo: required
dist: trusty
os: linux

script:
 - sudo apt-get -y install gcc-multilib
 - gcc -shared -fPIC -m32 -ldl libhookexecv.c -o libhookexecv.so
 - gcc -m32 -static preloaderhook.c -o wine-preloader_hook
 - strip libhookexecv.so wine-preloader_hook
 - bash -ex winedeploy.sh
 
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh libhookexecv.so ./Wine*.AppImage* ./Notepad*.AppImage* wineprefix.tar.gz

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
